"""Initial schema: all 6 entities

Revision ID: ab09aa026ab5
Revises: 
Create Date: 2025-11-06 14:56:46.794308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab09aa026ab5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.Enum('JPEG', 'PNG', name='imageformat'), nullable=False),
    sa.Column('upload_timestamp', sa.DateTime(), nullable=False),
    sa.Column('ocr_extracted_text', sa.String(), nullable=False),
    sa.Column('ocr_confidence_score', sa.Float(), nullable=False),
    sa.Column('contains_diagram', sa.Boolean(), nullable=False),
    sa.Column('diagram_description', sa.String(length=1000), nullable=True),
    sa.Column('preprocessing_applied', sa.JSON(), nullable=False),
    sa.Column('ocr_processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_images_file_path'), 'uploaded_images', ['file_path'], unique=True)
    op.create_index(op.f('ix_uploaded_images_ocr_confidence_score'), 'uploaded_images', ['ocr_confidence_score'], unique=False)
    op.create_index(op.f('ix_uploaded_images_upload_timestamp'), 'uploaded_images', ['upload_timestamp'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('domain', sa.Enum('ALGEBRA', 'GEOMETRY', 'CALCULUS', 'PROBABILITY', 'NUMBER_THEORY', 'COMBINATORICS', 'OTHER', name='mathdomain'), nullable=False),
    sa.Column('competencies', sa.JSON(), nullable=False),
    sa.Column('baseline_difficulty', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('ORIGINAL', 'REPHRASED', 'REVISED', name='problemsource'), nullable=False),
    sa.Column('source_type', sa.Enum('OCR', 'MANUAL_TEXT', name='sourcetype'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_image_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['problems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_image_id'], ['uploaded_images.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_domain'), 'problems', ['domain'], unique=False)
    op.create_index(op.f('ix_problems_parent_id'), 'problems', ['parent_id'], unique=False)
    op.create_index(op.f('ix_problems_source'), 'problems', ['source'], unique=False)
    op.create_index(op.f('ix_problems_source_type'), 'problems', ['source_type'], unique=False)
    op.create_index(op.f('ix_problems_uploaded_image_id'), 'problems', ['uploaded_image_id'], unique=False)
    op.create_table('quality_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('clarity_grammar_score', sa.Float(), nullable=False),
    sa.Column('logical_coherence_score', sa.Float(), nullable=False),
    sa.Column('mathematical_validity_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('thought_process', sa.String(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_assessments_overall_score'), 'quality_assessments', ['overall_score'], unique=False)
    op.create_index(op.f('ix_quality_assessments_problem_id'), 'quality_assessments', ['problem_id'], unique=False)
    op.create_table('rephrase_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_problem_id', sa.UUID(), nullable=False),
    sa.Column('final_problem_id', sa.UUID(), nullable=True),
    sa.Column('escalation_dimensions', sa.JSON(), nullable=False),
    sa.Column('iteration_count', sa.Integer(), nullable=False),
    sa.Column('quality_threshold', sa.Float(), nullable=False),
    sa.Column('final_status', sa.Enum('SUCCESS', 'MAX_ITERATIONS_EXCEEDED', 'ERROR', name='sessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['final_problem_id'], ['problems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rephrase_sessions_final_status'), 'rephrase_sessions', ['final_status'], unique=False)
    op.create_index(op.f('ix_rephrase_sessions_original_problem_id'), 'rephrase_sessions', ['original_problem_id'], unique=False)
    op.create_table('solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('thought_process', sa.String(), nullable=False),
    sa.Column('final_answer', sa.String(length=500), nullable=False),
    sa.Column('intermediate_steps', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_problem_id'), 'solutions', ['problem_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('OCR', 'REPHRASE', 'REVIEW', 'REVISE', 'SOLVER', name='agenttype'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('prompt_template', sa.String(), nullable=False),
    sa.Column('raw_llm_response', sa.String(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['rephrase_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_type'), 'agent_executions', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_executions_created_at'), 'agent_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_executions_session_id'), 'agent_executions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_executions_session_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_created_at'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_type'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_solutions_problem_id'), table_name='solutions')
    op.drop_table('solutions')
    op.drop_index(op.f('ix_rephrase_sessions_original_problem_id'), table_name='rephrase_sessions')
    op.drop_index(op.f('ix_rephrase_sessions_final_status'), table_name='rephrase_sessions')
    op.drop_table('rephrase_sessions')
    op.drop_index(op.f('ix_quality_assessments_problem_id'), table_name='quality_assessments')
    op.drop_index(op.f('ix_quality_assessments_overall_score'), table_name='quality_assessments')
    op.drop_table('quality_assessments')
    op.drop_index(op.f('ix_problems_uploaded_image_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_source_type'), table_name='problems')
    op.drop_index(op.f('ix_problems_source'), table_name='problems')
    op.drop_index(op.f('ix_problems_parent_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_domain'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_uploaded_images_upload_timestamp'), table_name='uploaded_images')
    op.drop_index(op.f('ix_uploaded_images_ocr_confidence_score'), table_name='uploaded_images')
    op.drop_index(op.f('ix_uploaded_images_file_path'), table_name='uploaded_images')
    op.drop_table('uploaded_images')
    # ### end Alembic commands ###
